import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#e4572e",
        "primary-container": "#e4572e",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        secondary: "#5a6675",
        "secondary-container": "#e4e9ef",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#101b28",
        error: "#e4572e",
        "error-container": "#e4572e",
        "on-error": "#ffffff",
        surface: "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#ffffff",
        "surface-container-high": "#e4e9ef",
        "surface-container-highest": "#e4e9ef",
        "surface-variant": "#e4e9ef",
        "surface-bright": "#ffffff",
        "surface-dim": "#e4e9ef",
        "on-surface": "#101b28",
        "on-surface-variant": "#5a6675",
        background: "#eef1f5",
        "on-background": "#101b28",
        outline: "#d3dae2",
        "outline-variant": "#d3dae2",
        "inverse-surface": "#101b28",
        "inverse-on-surface": "#eef1f5",
        "inverse-primary": "#ffffff",
        tertiary: "#101b28",
        "tertiary-container": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#101b28",
        "surface-tint": "#e4572e",
      },
      borderRadius: { DEFAULT: "0", lg: "0", xl: "0", full: "0" },
      fontFamily: {
        headline: ["Archivo", "Arial", "sans-serif"],
        body: ["IBM Plex Sans", "Arial", "sans-serif"],
        label: ["IBM Plex Mono", "Courier New", "monospace"],
      },
      boxShadow: { soft: "0 12px 28px rgba(16, 27, 40, 0.08)" },
    },
  },
  plugins: [],
} satisfies Config;
