import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#000000",
        "secondary-fixed-dim": "#3685c5",
        outline: "#000000",
        "surface-tint": "#000000",
        "on-surface": "#000000",
        "surface-container-low": "#ffffff",
        error: "#f37725",
        "on-primary-fixed": "#ffffff",
        secondary: "#3685c5",
        "primary-fixed": "#000000",
        primary: "#000000",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "surface-container": "#ffffff",
        "on-secondary-container": "#000000",
        "on-secondary": "#ffffff",
        "error-container": "#ffffff",
        surface: "#ffffff",
        "surface-container-highest": "#000000",
        "surface-container-high": "#ffffff",
        "outline-variant": "#000000",
        "primary-container": "#000000",
        "on-tertiary-container": "#000000",
        "secondary-container": "#ffffff",
        "inverse-primary": "#ffffff",
        "tertiary-fixed": "#ffffff",
        "on-secondary-fixed-variant": "#000000",
        "on-tertiary": "#ffffff",
        "on-error-container": "#000000",
        "secondary-fixed": "#3685c5",
        "on-tertiary-fixed-variant": "#000000",
        "surface-variant": "#ffffff",
        "primary-fixed-dim": "#000000",
        "surface-bright": "#ffffff",
        tertiary: "#000000",
        "on-primary": "#ffffff",
        "surface-dim": "#ffffff",
        "on-primary-container": "#ffffff",
        background: "#282725",
        "tertiary-fixed-dim": "#000000",
        "on-background": "#000000",
        "tertiary-container": "#ffffff",
        "on-surface-variant": "#000000",
        "inverse-on-surface": "#ffffff",
        "on-primary-fixed-variant": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Courier Prime", "Courier New", "monospace"],
        body: ["Verdana", "Geneva", "sans-serif"],
        label: ["Courier Prime", "Courier New", "monospace"],
      },
      boxShadow: {
        soft: "none",
      },
    },
  },
  plugins: [],
} satisfies Config;
