import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002113",
        "on-error": "#690005",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#9ed2b5",
        outline: "#86948a",
        "surface-tint": "#4edea3",
        "on-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        error: "#ffb4ab",
        "on-primary-fixed": "#002113",
        secondary: "#9ed2b5",
        "primary-fixed": "#6ffbbe",
        primary: "#4edea3",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#410005",
        "surface-container": "#201f1f",
        "on-secondary-container": "#91c4a8",
        "on-secondary": "#013824",
        "error-container": "#93000a",
        surface: "#131313",
        "surface-container-highest": "#353534",
        "surface-container-high": "#2a2a2a",
        "outline-variant": "#3c4a42",
        "primary-container": "#10b981",
        "on-tertiary-container": "#711419",
        "secondary-container": "#21523c",
        "inverse-primary": "#006c49",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-fixed-variant": "#1e4f3a",
        "on-tertiary": "#650911",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#baeed1",
        "on-tertiary-fixed-variant": "#842225",
        "surface-variant": "#353534",
        "primary-fixed-dim": "#4edea3",
        "surface-bright": "#3a3939",
        tertiary: "#ffb3af",
        "on-primary": "#003824",
        "surface-dim": "#131313",
        "on-primary-container": "#00422b",
        background: "#131313",
        "tertiary-fixed-dim": "#ffb3af",
        "on-background": "#e5e2e1",
        "tertiary-container": "#fc7c78",
        "on-surface-variant": "#bbcabf",
        "inverse-on-surface": "#313030",
        "on-primary-fixed-variant": "#005236",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        soft: "0 20px 50px rgba(0, 0, 0, 0.35)",
      },
    },
  },
  plugins: [],
} satisfies Config;
