version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: realtime-collab-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      target: deps
    container_name: realtime-collab-backend
    env_file:
      - ./backend/.env
    environment:
      CLIENT_URL: http://localhost:5173
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      target: deps
    container_name: realtime-collab-frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_SOCKET_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
