import { FormEvent, useEffect, useState } from "react";
import WorkspaceLayout from "../components/WorkspaceLayout";
import api from "../services/api";

type Provider = "webhook" | "slack" | "discord" | "teams";
type Integration = { id: string; name: string; provider: Provider; endpointUrl: string; eventTypes: string[]; enabled: boolean; hasSigningSecret: boolean; };
const events = ["document_updated", "document_shared", "document_commented", "document_deadline_created", "document_deadline_updated", "document_suggestion_created", "document_suggestion_decided"];

const IntegrationsPage = () => {
  const [items, setItems] = useState<Integration[]>([]);
  const [name, setName] = useState(""); const [provider, setProvider] = useState<Provider>("webhook"); const [endpointUrl, setEndpointUrl] = useState("");
  const [selectedEvents, setSelectedEvents] = useState<string[]>(events.slice(0, 3)); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = () => api.get<{ integrations: Integration[] }>("/integrations").then((response) => setItems(response.data.integrations));
  useEffect(() => { load().catch(() => setError("Integrations could not be loaded. Apply the latest Supabase schema first.")); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await api.post<{ integration: Integration; signingSecret?: string }>("/integrations", { name, provider, endpointUrl, eventTypes: selectedEvents }); setItems([response.data.integration, ...items]); setName(""); setEndpointUrl(""); setNotice(response.data.signingSecret ? `Created. Copy this signing secret now: ${response.data.signingSecret}` : "Integration created."); } catch (requestError: any) { setError(requestError.response?.data?.message || "Integration could not be created"); } finally { setBusy(false); } };
  const toggle = async (item: Integration) => { const response = await api.put<{ integration: Integration }>(`/integrations/${item.id}`, { enabled: !item.enabled }); setItems(items.map((value) => value.id === item.id ? response.data.integration : value)); };
  const remove = async (item: Integration) => { if (!window.confirm(`Delete ${item.name}?`)) return; await api.delete(`/integrations/${item.id}`); setItems(items.filter((value) => value.id !== item.id)); };
  const test = async (item: Integration) => { setError(""); setNotice(""); try { const response = await api.post<{ responseCode: number }>(`/integrations/${item.id}/test`); setNotice(`${item.name} accepted the test with HTTP ${response.data.responseCode}.`); } catch (requestError: any) { setError(requestError.response?.data?.message || "Test delivery failed"); } };
  return <WorkspaceLayout pageLabel="Automation" title="Integrations">
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
      <section className="rounded border border-white/5 bg-surface-container p-5"><p className="text-xs font-bold uppercase tracking-widest text-primary">Configured endpoints</p><div className="mt-5 space-y-3">{items.length ? items.map((item) => <div key={item.id} className="rounded border border-white/10 bg-surface-container-high p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold text-white">{item.name}</h2><p className="mt-1 break-all text-xs text-on-surface-variant">{item.provider.toUpperCase()} · {item.endpointUrl}</p><p className="mt-2 text-[10px] uppercase tracking-widest text-on-surface-variant">{item.eventTypes.length} events · {item.enabled ? "Enabled" : "Paused"}</p></div><div className="flex gap-2"><button className="emerald-muted-button px-3 py-2 text-xs" onClick={() => test(item)}>Test</button><button className="emerald-muted-button px-3 py-2 text-xs" onClick={() => toggle(item)}>{item.enabled ? "Pause" : "Enable"}</button><button className="rounded border border-error/20 px-3 py-2 text-xs text-error" onClick={() => remove(item)}>Delete</button></div></div></div>) : <p className="text-sm text-on-surface-variant">No integrations configured.</p>}</div></section>
      <form onSubmit={submit} className="rounded border border-white/5 bg-surface-container p-5"><p className="text-xs font-bold uppercase tracking-widest text-primary">Add destination</p><div className="mt-5 space-y-4"><input required maxLength={80} className="emerald-input" placeholder="Integration name" value={name} onChange={(e) => setName(e.target.value)} /><select className="emerald-input" value={provider} onChange={(e) => setProvider(e.target.value as Provider)}><option value="webhook">Generic webhook</option><option value="slack">Slack incoming webhook</option><option value="discord">Discord webhook</option><option value="teams">Microsoft Teams workflow webhook</option></select><input required type="url" className="emerald-input" placeholder="https://..." value={endpointUrl} onChange={(e) => setEndpointUrl(e.target.value)} /><div><p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-on-surface-variant">Events</p>{events.map((value) => <label key={value} className="mb-2 flex gap-2 text-xs text-white"><input type="checkbox" checked={selectedEvents.includes(value)} onChange={() => setSelectedEvents((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value])} />{value.replace(/^document_/, "").replace(/_/g, " ")}</label>)}</div>{error ? <p className="text-sm text-error">{error}</p> : null}{notice ? <p className="break-all text-sm text-primary">{notice}</p> : null}<button disabled={busy || !selectedEvents.length} className="emerald-primary-button w-full justify-center">{busy ? "Creating…" : "Create integration"}</button></div></form>
    </div>
  </WorkspaceLayout>;
};
export default IntegrationsPage;
