---
name: Secret Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TruffleHog scan (pull_request)
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified

      - name: TruffleHog scan (push)
        if: github.event_name == 'push'
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified
