---
name: Secret Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install TruffleHog
        run: |
          go install github.com/trufflesecurity/trufflehog/v3@latest

      - name: TruffleHog scan (pull_request)
        if: github.event_name == 'pull_request'
        run: |
          trufflehog git file://. \
            --since-commit ${{ github.event.pull_request.base.sha }} \
            --branch ${{ github.event.pull_request.head.sha }} \
            --only-verified

      - name: TruffleHog scan (push)
        if: github.event_name == 'push'
        run: |
          trufflehog git file://. \
            --since-commit ${{ github.event.before }} \
            --branch ${{ github.sha }} \
            --only-verified
